[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'solmate/=lib/solmate/src/']
optimizer_runs = 1000000
fuzz_runs = 1000

# See more config options https://github.com/gakonst/foundry/tree/master/config